/*
 * production-studio API
 * This is a REST API application made with Express.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ArrangedApiJobPriceOffersApi
 */
@Ignore
public class ArrangedApiJobPriceOffersApiTest {

    private final ArrangedApiJobPriceOffersApi api = new ArrangedApiJobPriceOffersApi();

    /**
     * delete job price offer
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiJobPriceOfferDeleteTest() throws ApiException {
        String offer = null;
        api.apiJobPriceOfferDelete(offer);

        // TODO: test validations
    }
    /**
     * get job price offer
     *
     * If you want to get a job price offer by ID Add offer&#x3D;offer_ID param.   Otherwise if you want to get a list of job price offers Add type&#x3D;all param and job&#x3D;job_ID param.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiJobPriceOfferGetTest() throws ApiException {
        String offer = null;
        api.apiJobPriceOfferGet(offer);

        // TODO: test validations
    }
    /**
     * fatch job price offer
     *
     * If you want to change the price add { \&quot;offer\&quot;: new_price } to body.  Otherwise the following code will be executed:  &#x60;await JobCrew.findByIdAndUpdate(req.body.jobCrew._id, { userRequestRemoval: true, });&#x60;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiJobPriceOfferPatchTest() throws ApiException {
        Object body = null;
        api.apiJobPriceOfferPatch(body);

        // TODO: test validations
    }
    /**
     * create job price offer
     *
     * create job price offer in \&quot;jobpriceoffers\&quot; table
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiJobPriceOfferPostTest() throws ApiException {
        Object body = null;
        api.apiJobPriceOfferPost(body);

        // TODO: test validations
    }
}
