/*
 * production-studio API
 * This is a REST API application made with Express.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ArrangedApiJobConversationApi
 */
@Ignore
public class ArrangedApiJobConversationApiTest {

    private final ArrangedApiJobConversationApi api = new ArrangedApiJobConversationApi();

    /**
     * send-message-job-conversation
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void newApiJobSendMessageJobConversationPostTest() throws ApiException {
        Object body = null;
        api.newApiJobSendMessageJobConversationPost(body);

        // TODO: test validations
    }
}
