/*
 * production-studio API
 * This is a REST API application made with Express.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ArrangedApiJobCrewApi
 */
@Ignore
public class ArrangedApiJobCrewApiTest {

    private final ArrangedApiJobCrewApi api = new ArrangedApiJobCrewApi();

    /**
     * get job crew
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiOfferConfirmGetTest() throws ApiException {
        String job = null;
        api.apiOfferConfirmGet(job);

        // TODO: test validations
    }
    /**
     * fatch offer crew
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiOfferConfirmPatchTest() throws ApiException {
        Object body = null;
        api.apiOfferConfirmPatch(body);

        // TODO: test validations
    }
    /**
     * create job crew
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiOfferConfirmPostTest() throws ApiException {
        Object body = null;
        api.apiOfferConfirmPost(body);

        // TODO: test validations
    }
}
