/*
 * production-studio API
 * This is a REST API application made with Express.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthenticationApi
 */
@Ignore
public class AuthenticationApiTest {

    private final AuthenticationApi api = new AuthenticationApi();

    /**
     * /auth/logout
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void authLogoutGetTest() throws ApiException {
        api.authLogoutGet();

        // TODO: test validations
    }
    /**
     * auth/signin
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void authSigninPostTest() throws ApiException {
        Object body = null;
        api.authSigninPost(body);

        // TODO: test validations
    }
    /**
     * /auth/signup
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void authSignupPostTest() throws ApiException {
        Object body = null;
        api.authSignupPost(body);

        // TODO: test validations
    }
    /**
     * /auth/user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void authUserGetTest() throws ApiException {
        api.authUserGet();

        // TODO: test validations
    }
    /**
     * /logged
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void loggedGetTest() throws ApiException {
        api.loggedGet();

        // TODO: test validations
    }
    /**
     * /verification/email
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void verificationEmailGetTest() throws ApiException {
        String email = null;
        String code = null;
        api.verificationEmailGet(email, code);

        // TODO: test validations
    }
    /**
     * /verification/email
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void verificationEmailPostTest() throws ApiException {
        Object body = null;
        api.verificationEmailPost(body);

        // TODO: test validations
    }
}
