/*
 * production-studio API
 * This is a REST API application made with Express.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StaticApi
 */
@Ignore
public class StaticApiTest {

    private final StaticApi api = new StaticApi();

    /**
     * Retrieve a list of body types from database.
     *
     * Retrieve a list of body types from database.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void staticBodyTypesGetTest() throws ApiException {
        String accept = null;
        Object response = api.staticBodyTypesGet(accept);

        // TODO: test validations
    }
    /**
     * Retrieve a list of countries from database.
     *
     * Retrieve a list of countries from database.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void staticCountriesGetTest() throws ApiException {
        String accept = null;
        Object response = api.staticCountriesGet(accept);

        // TODO: test validations
    }
    /**
     * Retrieve a list of currencies from database.
     *
     * Retrieve a list of currencies from database.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void staticCurrenciesGetTest() throws ApiException {
        String accept = null;
        Object response = api.staticCurrenciesGet(accept);

        // TODO: test validations
    }
    /**
     * Retrieve a list of currency-coins from database.
     *
     * Retrieve a list of currency-coins from database.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void staticCurrencyCoinsGetTest() throws ApiException {
        String accept = null;
        Object response = api.staticCurrencyCoinsGet(accept);

        // TODO: test validations
    }
    /**
     * Retrieve a list of ethnicities from database.
     *
     * Retrieve a list of ethnicities from database.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void staticEthnicitiesGetTest() throws ApiException {
        String accept = null;
        Object response = api.staticEthnicitiesGet(accept);

        // TODO: test validations
    }
    /**
     * Retrieve a list of eye_colors from database.
     *
     * Retrieve a list of eye_colors from database.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void staticEyeColorsGetTest() throws ApiException {
        String accept = null;
        Object response = api.staticEyeColorsGet(accept);

        // TODO: test validations
    }
    /**
     * Retrieve a list of hair colors from database.
     *
     * Retrieve a list of hair colors from database.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void staticHairColorsGetTest() throws ApiException {
        String accept = null;
        Object response = api.staticHairColorsGet(accept);

        // TODO: test validations
    }
    /**
     * Retrieve a list of languages from database.
     *
     * Retrieve a list of languages from database.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void staticLanguagesGetTest() throws ApiException {
        String accept = null;
        Object response = api.staticLanguagesGet(accept);

        // TODO: test validations
    }
    /**
     * Retrieve a list of locations categories en from database.
     *
     * Retrieve a list of locations categories en from database.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void staticLocationsCategoriesEnGetTest() throws ApiException {
        String accept = null;
        Object response = api.staticLocationsCategoriesEnGet(accept);

        // TODO: test validations
    }
    /**
     * Retrieve a list of skills from database.
     *
     * Retrieve a list of skills from database.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void staticSkillsGetTest() throws ApiException {
        String accept = null;
        Object response = api.staticSkillsGet(accept);

        // TODO: test validations
    }
}
